# Generated by Django 4.2.7 on 2025-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
