# Generated by Django 5.2.1 on 2025-11-12 12:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum advertised price for this service (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum advertised price for this service (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
