# Generated by Django 4.2.7 on 2025-10-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_stock_quantity_and_more'),
    ]
    operations = []
