# Generated by Django 4.2.7 on 2025-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipmentwishlist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpurchase',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
    ]
