# Generated by Django 5.2.1 on 2025-11-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof_file',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
    ]
