# Generated by Django 5.2.1 on 2025-11-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_image'),
        ('payments', '0002_payment_payment_proof_file'),
        ('pharmacy', '0003_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='equipment_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='equipment.equipmentpurchase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='equipment_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='equipment.equipmentrental'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pharmacy_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pharmacy.pharmacyorder'),
        ),
    ]
