# Generated by Django on 2025-11-04 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_equipment_purchase_payment_equipment_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, choices=[('cash', 'Cash After Service'), ('online', 'Online Payment (QR)')]),
        ),
    ]
