# Generated by Django 4.2.7 on 2025-10-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentWishlist',
        ),
    ]
