# Generated by Django 5.2.1 on 2025-11-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicine_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('placed', 'Order Placed'), ('payment', 'Payment'), ('prescription_uploaded', 'Prescription Uploaded'), ('prescription_verified', 'Prescription Verified'), ('status', 'Status Update'), ('delivered', 'Delivered'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pharmacy.pharmacyorder')),
            ],
            options={
                'db_table': 'pharmacy_order_activities',
                'ordering': ['created_at'],
            },
        ),
    ]
