# Generated by Django 5.2.1 on 2025-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_personalappointment_appointmentreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price set by admin/provider after assessment (overrides service_price in totals)', max_digits=10, null=True),
        ),
    ]
